name: visshous 
base: core18
version: '0.1' 
summary: magically transport your vim config to remote servers
description: |
  ViSSHous is a simple tool which helps you carry your vim profile everywhere across SSH sessions, by embedding your vim configuration within SSH itself. 
grade: devel 
confinement: devmode
  

apps:
  visshous: 
    command: inotifywait -e modify -e create $HOME/.vimrc; ./vissh;
    daemon: simple
    restart-condition: always

parts:
  visshous:
    stage-packages:
      - inotify-tools
    source: https://github.com/gWOLF3/viSSHous/archive/v0.0.3.tar.gz
    plugin: dump
    organize:
      vissh: /usr/bin/vissh
