name: visshous 
base: core18
version: '0.1' 
summary: magically transport your vim config to remote servers
description: |
  ViSSHous is a simple tool which helps you carry your vim profile everywhere across SSH sessions, by embedding your vim configuration within SSH itself. 
grade: devel 
confinement: strict

plugs: 
  vim-files:
    interface: personal-files
    read: 
    - $HOME/.vimrc
    - $HOME/.vim
    - $HOME/.ssh/viSSHous
    write: 
    - $HOME/.vimrc
    - $HOME/.vim
    - $HOME/.bashrc
    - $HOME/.zshrc
    - $HOME/.ssh/viSSHous

apps:
  visshous: 
    plugs:
    - vim-files
    command: bash -c $SNAP/vissh_snap
    daemon: simple
    restart-condition: always
    restart-delay: 3s
    passthrough:
      daemon-scope: user

parts:
  visshous:
    stage-packages:
      - inotify-tools
    source: https://github.com/gWOLF3/viSSHous/archive/v0.0.16.tar.gz
    plugin: dump
